### ISSUE TITLE
垃圾呀，下来都跑不了

### ISSUE THREAD

**Issue by sxm20074428** [yahoo/mysql_perf_analyzer#23]
Thu May 11 18:11:12 CST 2017 Usage: java -classpath ... com.yahoo.dba.tools.myperfserver.App -f config_file_path -j jettyhome -p port -c webcontextroot -k workingDir -l logpath -w war_file
Use configuration file: config_sample.properties
java.io.FileNotFoundException: myperf.pid (没有那个文件或目录)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at java.io.FileReader.<init>(FileReader.java:58)
	at com.yahoo.dba.tools.myperfserver.App.getHistoryPid(App.java:468)
	at com.yahoo.dba.tools.myperfserver.App.checksRunningOfAnotherServerInstance(App.java:111)
	at com.yahoo.dba.tools.myperfserver.App.main(App.java:93)
Thu May 11 18:11:13 CST 2017 Create working dir at /usr/local/myperfserver/./work
Thu May 11 18:11:13 CST 2017 Use working directory /usr/local/myperfserver/./work
Thu May 11 18:11:13 CST 2017 Create log directory at /usr/local/myperfserver/./logs
Thu May 11 18:11:13 CST 2017 Use log directory /usr/local/myperfserver/./logs
Thu May 11 18:11:13 CST 2017 Use jetty home /home/xrao/mpa
Thu May 11 18:11:13 CST 2017 Cannot find war file at location /home/xrao/mpa/webapps/myperf.war
Server not started.
Thu May 11 18:11:43 CST 2017 Usage: java -classpath ... com.yahoo.dba.tools.myperfserver.App -f config_file_path -j jettyhome -p port -c webcontextroot -k workingDir -l logpath -w war_file
Use configuration file: config_sample.properties
java.lang.NumberFormatException: null
	at java.lang.Integer.parseInt(Integer.java:542)
	at java.lang.Integer.parseInt(Integer.java:615)
	at com.yahoo.dba.tools.myperfserver.App.getHistoryPid(App.java:472)
	at com.yahoo.dba.tools.myperfserver.App.checksRunningOfAnotherServerInstance(App.java:111)
	at com.yahoo.dba.tools.myperfserver.App.main(App.java:93)
Thu May 11 18:11:43 CST 2017 Use working directory /usr/local/myperfserver/./work
Thu May 11 18:11:43 CST 2017 Use log directory /usr/local/myperfserver/./logs
Thu May 11 18:11:43 CST 2017 Use jetty home /home/xrao/mpa
Thu May 11 18:11:43 CST 2017 Cannot find war file at location /home/xrao/mpa/webapps/myperf.war
Server not started.

**Comment by xrao** [comment]
Added default configuration file config_default.properties and point to it.  Original one is just a sample.
